# Generated by Django 2.2 on 2019-04-12 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, max_length=500)),
                ('id_user', models.IntegerField(default=0)),
                ('room_name', models.CharField(default='dialog-1-5', max_length=500)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(blank=True, upload_to='posts-images')),
                ('sound', models.FileField(blank=True, upload_to='musics')),
            ],
        ),
    ]
