# Generated by Django 3.0.4 on 2020-06-09 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_profile', '0002_profilefile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profilefile',
            name='file',
            field=models.FileField(upload_to='files'),
        ),
    ]
